spring:
  application:
    name: user
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${POSTGRES_USER_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: ${POSTGRES_JDBC_DRIVER}
  kafka:
    bootstrap-servers: ${KAFKA}

server:
  port: ${USER}