services:
  postgres:
    image: postgres
    ports:
      - "100:5432"
    networks:
      - auth-network
      - user-network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
  auth:
    image: portfolio/auth
    depends_on:
      - postgres
      - redis
    ports:
      - "1000:1000"
    networks:
      - auth-network
      - user-network
    env_file:
      - .env

  user:
    image: portfolio/user
    depends_on:
      - postgres
      - kafka
    ports:
      - "1001:1001"
    networks:
      - user-network
    env_file:
      - .env
    
  redis:
    image: redis
    ports:
      - "101:6379"
    networks:
      - auth-network
    env_file:
      - .env
    
  kafka:
    image: apache/kafka
    ports:
      - "102:9092"
    networks:
      - user-network

networks:
  auth-network:
    driver: bridge
  user-network:
    driver: bridge
