services:
  postgres:
    image: postgres
    ports:
      - "100:5432"
    networks:
      - user-network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_USER_PASSWORD}
    
  user:
    image: portfolio/auth
    depends_on:
      - postgres
      - redis
    ports:
      - "1001:1001"
    networks:
      - user-network
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - "101:6379"
    networks:
      - user-network
    env_file:
      - .env
    
  kafka:
    image: apache/kafka
    ports:
      - "102:9092"
    networks:
      - user-network

networks:
  user-network:
    driver: bridge